### ISSUE TITLE
Swift3?

### ISSUE THREAD

**Issue by Sweeper777** [abdullahselek/ASToast#1]
I tried converting this to Swift 3 syntax using the Xcode migrator. But there are 7 errors in ASToast. Can you do a Swift 3 version?

If you already support Swift 3, can you tell me what to write in my pod file in order to install the swift 3 version?

**Comment by abdullahselek** [comment]
I have just published version 1.0.4 you can use it for Swift 3. Please let me know the result then I will close the issue.

**Comment by Sweeper777** [comment]
Thank you!
