### ISSUE TITLE
I want to adjust the duration from 3 sec

### ISSUE THREAD

**Issue by samad5353** [abdullahselek/ASToast#2]
` static let ASToastDuration = TimeInterval(0.5)`

any option to edit this without editing pod file?

**Comment by abdullahselek** [comment]
Hi @samad5353, yes it is possible. Some of the "makeToast" functions have duration parameter which you can set a TimeInterval.

**Comment by samad5353** [comment]
I want to make the initial delay of toast from 3 to 0.5

**Comment by abdullahselek** [comment]
ok, when you set the duration parameter initial delay changes

**Comment by samad5353** [comment]
I tried to set the duration like 
`self.view.showToast(customView, duration: TimeInterval(1.0), position: ASToastPosition.ASToastPositionCenter.rawValue as AnyObject)`
actual issue, is the initial delay to show the toast. 
If I modify the  duration parameter, initial delay  changes as u said. but at the same time. toast will disappear.
