### ISSUE TITLE
Can I set the fade in and fade out time of toasts?

### ISSUE THREAD

**Issue by Sweeper777** [abdullahselek/ASToast#3]
Currently, the toasts take a little more than 1 whole second to fade in, meaning that if I show a toast for one second, it disappears before it even fully fades in. The fade in animation just takes too long. Can I set fade in and fade out durations?

**Comment by abdullahselek** [comment]
There is an available function which gets duration parameter as an time interval you can use it.

**Comment by Sweeper777** [comment]
Yes, I know that there is a function that takes a `duration` parameter. But that parameter seems to only control the amount of time that the toast is shown, not the fade in and fade out time. The problem is that I want the toast to fade in more quickly.

**Comment by abdullahselek** [comment]
For now this not supported, but I am going to add this feature too, thanks.

**Comment by abdullahselek** [comment]
@Sweeper777 you can checkout the latest version for proper animation and can use the duration parameter.

**Comment by Sweeper777** [comment]
I feel like the fade in animation is still quite slow. It seems like that you're passing `duration` as the fade in animation duration:

        UIView.animate(withDuration: duration, delay: 0.0, options: UIViewAnimationOptions.allowUserInteraction, animations: { () -> Void in
            toastView.alpha = 1.0
        }) { (_) -> Void in

        }

I changed it to `Constants.ToastFadeDuration` and it works. I will send a pull request tomorrow, adding fade in duration parameters.

**Comment by abdullahselek** [comment]
@Sweeper777 I am closing this issue, after the merge should be fine.
