### ISSUE TITLE
Why does makeToast takes a AnyObject? as a parameter for position?

### ISSUE THREAD

**Issue by Sweeper777** [abdullahselek/ASToast#4]
One overload of `makeToast` is like this:

    public func makeToast(_ message: String,
                          duration: TimeInterval,
                          position: AnyObject?, // Why is this AnyObject? ?
                          backgroundColor: UIColor?,
                          titleColor: UIColor?,
                          messageColor: UIColor?)

`position` should be of type `ASToastPosition?`

Also, the enums should really be renamed swiftily.

```
public enum ASToastPosition: String {
    case top = "ASToastPositionTop",
    center = "ASToastPositionCenter",
    bottom = "ASToastPositionBotom"
}
```

**Comment by abdullahselek** [comment]
Working on it please wait for the next version ;)

**Comment by abdullahselek** [comment]
@Sweeper777 you can checkout version 1.0.7

**Comment by Sweeper777** [comment]
Thanks!
